FROM  mcr.microsoft.com/dotnet/core/sdk:3.1 as build
WORKDIR source
COPY . /source

RUN dotnet restore
RUN dotnet build
RUN dotnet publish -o /source/out

FROM  mcr.microsoft.com/dotnet/core/aspnet:3.1 as runtime

 

ENV ASPNETCORE_URLS=http://+:5000
ENV ASPNETCORE_ENVIRONMENT docker


RUN apt-get update
RUN apt-get install -y nginx

WORKDIR /app
COPY startup.sh .
RUN chmod 755 /app/startup.sh
 
RUN rm /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx
COPY --from=build /source/out/. . 
 
RUN  ls
EXPOSE 80
 
CMD ["sh", "/app/startup.sh"]


# ENTRYPOINT dotnet webapp.dll